openapi: 3.0.0
info:
  title: Ana
  version: 1.0.0
servers:
  - url: http://{{anal_local}}
  - url: https://api.hyrd.de
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Predict
paths:
  /ana/api/ping:
    get:
      tags:
        - Predict
      summary: Ping Pong
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /ana/api/topics:
    get:
      tags:
        - Predict
      summary: Get Topic list
      description: >-
        ## Overview


        This API endpoint allows you to retrieve topic predictions based on the
        provided conversation data. It processes conversations associated with a
        specific company and returns the predicted topics along with their
        occurrence counts.


        ## Endpoint


        `GET /ana/api/topics`


        **Method:** GET


        **Request Headers:**


        - `Authorization`: `Bearer` (required for authentication)
            

        ## Success Response


        **Code:** `200 OK`


        **Content:**


        ``` json

        {
            "status": 200,
            "message": "Predictions retrieved successfully.",
            "data": [
                {
                    "topic": "Corporate Social Responsibility and Environmental Initiatives",
                    "count": 1
                },
                {
                    "topic": "Team dynamics and leadership styles at Miro",
                    "count": 3
                },
                {
                    "topic": "Employee engagement and recognition at Miro",
                    "count": 4
                },
                {
                    "topic": "Miro's corporate evolution and growth",
                    "count": 1
                },
                {
                    "topic": "Miro's growth and hiring plans",
                    "count": 6
                },
                {
                    "topic": "Employee wellness and health programs at Miro",
                    "count": 2
                },
                {
                    "topic": "Company culture and values at Miro",
                    "count": 65
                },
                {
                    "topic": "Job Application Status Inquiries at Miro",
                    "count": 128
                }
            ]
        }

         ```

        ## Error Responses


        **Code:** `404 Not Found`


        **Message:** No predictions found for the provided company.  

        **Possible reason:** There are no conversations with the defined company
        id.


        **Content:**


        ``` json

        {
            "status": 404,
            "message": "No predictions found for the provided company.",
            "data": []
        }

         ```

        **Code:** `404 Not Found`


        **Message:** No predictions found for the provided company.  

        **Possible reason:** There are no conversations with the defined company
        id.


        **Content:**


        ``` json

        {
            "status": 404,
            "message": "No predictions found for the provided company.",
            "data": []
        }

         ```

        **Code:** `500 Internal Server Error`


        **Message:** Failed to retrieve predictions.


        **Content:**


        ``` json

        {
            "detail": "Failed to retrieve predictions: <error_message>"
        }

         ```
      security:
        - bearerAuth: []
      parameters:
        - name: accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Aut
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4Mjc3OCIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY3ODcyMzIzNCwiZXhwIjoxNjgxMzE1MjM0LCJqdGkiOiJkMTQyNjE1Yy1kYTdiLTRlMjYtODEwNi02ZDI4MTAzMzRjOWMifQ.iKf1q3_PTaTOkEAnoUEbtEkgcJbE1iALGRd49LjIDm4
        - name: per_page
          in: query
          schema:
            type: integer
          example: '25'
        - name: lang
          in: query
          schema:
            type: string
          example: de
      responses:
        '200':
          description: "Success"
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: Success Example
                  value:
                    status: 200
                    message: Predictions retrieved successfully.
                    data:
                      - topic: "Corporate Social Responsibility and Environmental Initiatives"
                        count: 1
                      - topic: "Team dynamics and leadership styles at Miro"
                        count: 3
                      - topic: "Employee engagement and recognition at Miro"
                        count: 4
                      - topic: "Miro's corporate evolution and growth"
                        count: 1
                      - topic: "Miro's growth and hiring plans"
                        count: 6
                      - topic: "Employee wellness and health programs at Miro"
                        count: 2
                      - topic: "Company culture and values at Miro"
                        count: 65
                      - topic: "Job Application Status Inquiries at Miro"
                        count: 128
        '404':
          description: "Not Found"
          content:
            application/json:
              schema:
                type: object
              example:
                status: 404
                message: "No predictions found for the provided company."
                data: []
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                type: object
              example:
                detail: "Failed to retrieve predictions: <error_message>"
